export const GET_USERS_IN_ROOM = 'GET_USERS_IN_ROOM';
export const TOGGLE_POPUP = 'TOGGLE_POPUP';
export const TOGGLE_PARTICIPANTS_TAB = 'TOGGLE_PARTICIPANTS_TAB';
export const SAVE_INTERVAL_FOR_USER_COUNT = 'SAVE_INTERVAL_FOR_USER_COUNT';
export const CLEAR_INTERVAL_FOR_USER_COUNT = 'CLEAR_INTERVAL_FOR_USER_COUNT';
export const EXPIRED_GUEST = 'EXPIRED_GUEST';
export const MISSING_USER = 'MISSING_USER';
